/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejos;
import clases.ComplejosDivisionCeroException;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo_Escobar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtImag1 = new javax.swing.JTextField();
        txtReal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtImag2 = new javax.swing.JTextField();
        txtReal2 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtImag3 = new javax.swing.JTextField();
        txtReal3 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Números complejos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setText("(                     +                    i  )");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtImag1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtImag1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImag1KeyTyped(evt);
            }
        });
        jPanel1.add(txtImag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));

        txtReal1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtReal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal1KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setText("(                    +                    i  )");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 20));

        txtImag2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtImag2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImag2KeyTyped(evt);
            }
        });
        jPanel1.add(txtImag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, -1));

        txtReal2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtReal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal2KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, -1));

        cmbOperacion.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division", " " }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel4.setText("(                    +                     i  )");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 20));

        txtImag3.setEditable(false);
        txtImag3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jPanel1.add(txtImag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 70, -1));

        txtReal3.setEditable(false);
        txtReal3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jPanel1.add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 70, -1));

        cmdCalcular.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        cmdLimpiar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("=");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 240));

        setSize(new java.awt.Dimension(584, 275));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
     
        int operacion;
        double real1, real2, imaginario1, imaginario2;
        Complejos c1;
        Complejos c2;
        Complejos c3 = null;
        int sw = 1;

        if (txtReal1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número real del complejo  #1", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal1.requestFocusInWindow();
        } else if (txtImag1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número imaginario del complejo #1", "Error", JOptionPane.ERROR_MESSAGE);
            txtImag1.requestFocusInWindow();
        } else if (txtReal2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número real del complejo #2", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal2.requestFocusInWindow();
        } else if (txtImag2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número imaginario del complejo #2", "Error", JOptionPane.ERROR_MESSAGE);
            txtImag2.requestFocusInWindow();
        } else {
            try {
                real1 = Integer.parseInt(txtReal1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número real del complejo 1 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtReal1.requestFocusInWindow();
                txtReal1.selectAll();
                sw = 0;
            }
            try {
                imaginario1 = Integer.parseInt(txtImag1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número imaginario del complejo 1 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtImag1.requestFocusInWindow();
                txtImag1.selectAll();
                sw = 0;
            }
            try {
                real2 = Integer.parseInt(txtReal2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número real del complejo 2 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtReal2.requestFocusInWindow();
                txtReal2.selectAll();
                sw = 0;
            }
            try {
                imaginario2 = Integer.parseInt(txtImag2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número imaginario del complejo 2 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtImag2.requestFocusInWindow();
                txtImag2.selectAll();
                sw = 0;
            }
            if (sw == 1) {
                operacion = cmbOperacion.getSelectedIndex();
                real1 = Integer.parseInt(txtReal1.getText());
                imaginario1 = Integer.parseInt(txtImag1.getText());
                real2 = Integer.parseInt(txtReal2.getText());
                imaginario2 = Integer.parseInt(txtImag2.getText());

                try {
                    c1 = new Complejos(real1, imaginario1);
                    c2 = new Complejos(real2, imaginario2);

                    switch (operacion) {
                        case 0:
                            c3 = c1.sumar(c2);
                            break;
                        case 1:
                            c3 = c1.restar(c2);
                            break;
                        case 2:
                            c3 = c1.multiplicar(c2);
                            break;
                        case 3:
                            c3 = c1.dividir(c2);
                            break;
                    }
                    txtReal3.setText("" + c3.getReal());
                    txtImag3.setText("" + c3.getImag());
                } catch (ComplejosDivisionCeroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    if (real2 == 0) {
                        txtReal2.requestFocusInWindow();
                        txtReal2.selectAll();
                    } else if (imaginario2 == 0) {
                        txtImag2.requestFocusInWindow();
                        txtImag2.selectAll();
                    }
                }
            }
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
   
        txtReal1.setText("");
        txtImag1.setText("");
        txtReal2.setText("");
        txtImag2.setText("");
        txtReal3.setText("");
        txtImag3.setText("");
        cmbOperacion.setSelectedIndex(0);
        txtReal1.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtReal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal1KeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtReal1KeyTyped

    private void txtImag1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImag1KeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtImag1KeyTyped

    private void txtReal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal2KeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtReal2KeyTyped

    private void txtImag2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImag2KeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtImag2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImag1;
    private javax.swing.JTextField txtImag2;
    private javax.swing.JTextField txtImag3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
